// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package aichat

import (
	"context"
	"fmt"
	"github.com/cloudwego/kitex/pkg/streaming"
	"github.com/li1553770945/personal-aichat-service/kitex_gen/base"
)

const (
	EventTypeMessage = "message"

	EventTypeEventId = "event_id"

	EventTypeMCP = "mcp"
)

type SendMessageReq struct {
	Message string `thrift:"message,1,required" frugal:"1,required,string" json:"message"`
}

func NewSendMessageReq() *SendMessageReq {
	return &SendMessageReq{}
}

func (p *SendMessageReq) InitDefault() {
}

func (p *SendMessageReq) GetMessage() (v string) {
	return p.Message
}
func (p *SendMessageReq) SetMessage(val string) {
	p.Message = val
}

func (p *SendMessageReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendMessageReq(%+v)", *p)
}

var fieldIDToName_SendMessageReq = map[int16]string{
	1: "message",
}

type SendMessageResp struct {
	BaseResp  *base.BaseResp `thrift:"baseResp,1,required" frugal:"1,required,base.BaseResp" json:"baseResp"`
	EventType string         `thrift:"event_type,2,required" frugal:"2,required,string" json:"event_type"`
	Data      string         `thrift:"data,3,required" frugal:"3,required,string" json:"data"`
}

func NewSendMessageResp() *SendMessageResp {
	return &SendMessageResp{}
}

func (p *SendMessageResp) InitDefault() {
}

var SendMessageResp_BaseResp_DEFAULT *base.BaseResp

func (p *SendMessageResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return SendMessageResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *SendMessageResp) GetEventType() (v string) {
	return p.EventType
}

func (p *SendMessageResp) GetData() (v string) {
	return p.Data
}
func (p *SendMessageResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}
func (p *SendMessageResp) SetEventType(val string) {
	p.EventType = val
}
func (p *SendMessageResp) SetData(val string) {
	p.Data = val
}

func (p *SendMessageResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *SendMessageResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendMessageResp(%+v)", *p)
}

var fieldIDToName_SendMessageResp = map[int16]string{
	1: "baseResp",
	2: "event_type",
	3: "data",
}

type AIChatService interface {
	SendMessage(ctx context.Context, req *SendMessageReq, stream AIChatService_SendMessageServer) (err error)
}

type AIChatServiceSendMessageArgs struct {
	Req *SendMessageReq `thrift:"req,1" frugal:"1,default,SendMessageReq" json:"req"`
}

func NewAIChatServiceSendMessageArgs() *AIChatServiceSendMessageArgs {
	return &AIChatServiceSendMessageArgs{}
}

func (p *AIChatServiceSendMessageArgs) InitDefault() {
}

var AIChatServiceSendMessageArgs_Req_DEFAULT *SendMessageReq

func (p *AIChatServiceSendMessageArgs) GetReq() (v *SendMessageReq) {
	if !p.IsSetReq() {
		return AIChatServiceSendMessageArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AIChatServiceSendMessageArgs) SetReq(val *SendMessageReq) {
	p.Req = val
}

func (p *AIChatServiceSendMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AIChatServiceSendMessageArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIChatServiceSendMessageArgs(%+v)", *p)
}

var fieldIDToName_AIChatServiceSendMessageArgs = map[int16]string{
	1: "req",
}

type AIChatServiceSendMessageResult struct {
	Success *SendMessageResp `thrift:"success,0,optional" frugal:"0,optional,SendMessageResp" json:"success,omitempty"`
}

func NewAIChatServiceSendMessageResult() *AIChatServiceSendMessageResult {
	return &AIChatServiceSendMessageResult{}
}

func (p *AIChatServiceSendMessageResult) InitDefault() {
}

var AIChatServiceSendMessageResult_Success_DEFAULT *SendMessageResp

func (p *AIChatServiceSendMessageResult) GetSuccess() (v *SendMessageResp) {
	if !p.IsSetSuccess() {
		return AIChatServiceSendMessageResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AIChatServiceSendMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*SendMessageResp)
}

func (p *AIChatServiceSendMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AIChatServiceSendMessageResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIChatServiceSendMessageResult(%+v)", *p)
}

var fieldIDToName_AIChatServiceSendMessageResult = map[int16]string{
	0: "success",
}

type AIChatService_SendMessageServer streaming.ServerStreamingServer[SendMessageResp]
