// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"github.com/li1553770945/personal-aichat-service/biz/infra/config"
	"github.com/li1553770945/personal-aichat-service/biz/infra/log"
	"github.com/li1553770945/personal-aichat-service/biz/infra/rpc"
	"github.com/li1553770945/personal-aichat-service/biz/infra/trace"
	"github.com/li1553770945/personal-aichat-service/biz/internal/service"
)

// Injectors from wire.go:

func GetContainer(env string) *Container {
	configConfig := config.GetConfig(env)
	traceLogger := log.InitLog()
	traceStruct := trace.InitTrace(configConfig)
	client := rpc.NewAuthClient(configConfig)
	iaiChatService := service.NewAChatService(client, configConfig)
	container := NewContainer(configConfig, traceLogger, traceStruct, iaiChatService)
	return container
}
