// Code generated by Kitex v0.15.4. DO NOT EDIT.

package aichatservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	aichat "github.com/li1553770945/personal-aichat-service/kitex_gen/aichat"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SendMessage": kitex.NewMethodInfo(
		sendMessageHandler,
		newAIChatServiceSendMessageArgs,
		newAIChatServiceSendMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingServer),
	),
}

var (
	aIChatServiceServiceInfo = NewServiceInfo()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return aIChatServiceServiceInfo
}

// NewServiceInfo creates a new ServiceInfo
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo()
}

func newServiceInfo() *kitex.ServiceInfo {
	serviceName := "AIChatService"
	handlerType := (*aichat.AIChatService)(nil)
	extra := map[string]interface{}{
		"PackageName": "aichat",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         serviceMethods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func sendMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	st, err := streaming.GetServerStreamFromArg(arg)
	if err != nil {
		return err
	}
	stream := streaming.NewServerStreamingServer[aichat.SendMessageResp](st)
	req := new(aichat.SendMessageReq)
	if err := stream.RecvMsg(ctx, req); err != nil {
		return err
	}
	return handler.(aichat.AIChatService).SendMessage(ctx, req, stream)
}

func newAIChatServiceSendMessageArgs() interface{} {
	return aichat.NewAIChatServiceSendMessageArgs()
}

func newAIChatServiceSendMessageResult() interface{} {
	return aichat.NewAIChatServiceSendMessageResult()
}

type kClient struct {
	c  client.Client
	sc client.Streaming
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c:  c,
		sc: c.(client.Streaming),
	}
}

func (p *kClient) SendMessage(ctx context.Context, req *aichat.SendMessageReq) (AIChatService_SendMessageClient, error) {
	st, err := p.sc.StreamX(ctx, "SendMessage")
	if err != nil {
		return nil, err
	}
	stream := streaming.NewServerStreamingClient[aichat.SendMessageResp](st)
	if err := stream.SendMsg(ctx, req); err != nil {
		return nil, err
	}
	if err := stream.CloseSend(ctx); err != nil {
		return nil, err
	}
	return stream, nil
}
