// Code generated by Kitex v0.15.4. DO NOT EDIT.

package aichatservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	streamcall "github.com/cloudwego/kitex/client/callopt/streamcall"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	transport "github.com/cloudwego/kitex/transport"
	aichat "github.com/li1553770945/personal-aichat-service/kitex_gen/aichat"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SendMessage(ctx context.Context, req *aichat.SendMessageReq, callOptions ...streamcall.Option) (stream AIChatService_SendMessageClient, err error)
}

type AIChatService_SendMessageClient streaming.ServerStreamingClient[aichat.SendMessageResp]

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.TTHeaderStreaming))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAIChatServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAIChatServiceClient struct {
	*kClient
}

func (p *kAIChatServiceClient) SendMessage(ctx context.Context, req *aichat.SendMessageReq, callOptions ...streamcall.Option) (stream AIChatService_SendMessageClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, streamcall.GetCallOptions(callOptions))
	return p.kClient.SendMessage(ctx, req)
}
