// Code generated by Kitex v0.15.4. DO NOT EDIT.
package aichatservice

import (
	server "github.com/cloudwego/kitex/server"
	aichat "github.com/li1553770945/personal-aichat-service/kitex_gen/aichat"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler aichat.AIChatService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler aichat.AIChatService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
